// Package editor opens files in the user's preferred external editor.
// It uses tea.ExecProcess so the Bubble Tea TUI suspends cleanly, restoring
// the alt-screen and full state once the editor process exits.
package editor

import (
	"fmt"
	"os"
	"os/exec"

	tea "github.com/charmbracelet/bubbletea"
)

// DoneMsg is sent after the editor process exits.
type DoneMsg struct {
	Path string
	Err  error
}

// Open suspends the TUI, launches the preferred editor on path, and sends
// DoneMsg when it returns.
func Open(path string) tea.Cmd {
	editorBin := findEditor()
	cmd := exec.Command(editorBin, path)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return tea.ExecProcess(cmd, func(err error) tea.Msg {
		return DoneMsg{Path: path, Err: err}
	})
}

// FindOrCreate looks for a vars file for entityName under baseDir:
//
//	baseDir/<subdir>/<entityName>.yml
//	baseDir/<subdir>/<entityName>.yaml
//	baseDir/<subdir>/<entityName>/main.yml
//
// If none exists, it creates baseDir/<subdir>/<entityName>.yml (with a header
// comment) and returns that path. Returns an error only if creation fails.
func FindOrCreate(baseDir, subdir, entityName string) (string, error) {
	candidates := []string{
		fmt.Sprintf("%s/%s/%s.yml", baseDir, subdir, entityName),
		fmt.Sprintf("%s/%s/%s.yaml", baseDir, subdir, entityName),
		fmt.Sprintf("%s/%s/%s/main.yml", baseDir, subdir, entityName),
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}
	// Create a new .yml file.
	newPath := candidates[0]
	if err := os.MkdirAll(fmt.Sprintf("%s/%s", baseDir, subdir), 0o750); err != nil {
		return "", err
	}
	header := fmt.Sprintf("# Variables for %s\n# Generated by lazyansible\n---\n\n", entityName)
	if err := os.WriteFile(newPath, []byte(header), 0o640); err != nil {
		return "", err
	}
	return newPath, nil
}

// findEditor returns the editor binary to use.
// Priority: $VISUAL → $EDITOR → nano → vim → vi.
func findEditor() string {
	for _, env := range []string{"VISUAL", "EDITOR"} {
		if v := os.Getenv(env); v != "" {
			return v
		}
	}
	for _, bin := range []string{"nano", "vim", "vi"} {
		if _, err := exec.LookPath(bin); err == nil {
			return bin
		}
	}
	return "vi"
}
